sudo: required
services:
  - docker
language: generic

before_install: 
  - docker build -t ppsrivastava/react-test -f ./client/Dockerfile.dev ./client --progress plain

script: 
  - docker run -e CI=true ppsrivastava/react-test npm test -- --coverage

after_success: 
  - docker build -t ppsrivastava/multi-client ./client --progress plain
  - docker build -t ppsrivastava/multi-server ./server --progress plain
  - docker build -t ppsrivastava/multi-worker ./worker --progress plain
  - docker build -t ppsrivastava/multi-nginx ./nginx --progress plain
  # Login to Docker CLI first (docker login - CMD)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ppsrivastava/multi-client
  - docker push ppsrivastava/multi-server
  - docker push ppsrivastava/multi-worker
  - docker push ppsrivastava/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-471112754900'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY